require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - node_modules/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 30
  Exclude:
    - app/controllers/concerns/create_notification.rb

Metrics/ParameterLists:
  Enabled: false

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/InverseOf:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - app/helpers/api/v1/user_challenge_helper.rb
    - app/controllers/concerns/create_notification.rb

GlobalVars:
  AllowedVariables:
    - $redis
